### ISSUE TITLE
Unhandled Exception for Nonexistant Savefiles

### ISSUE THREAD

**Issue by gwonny** [lawrencea13/LethalCompanySaveManager#4]
![image](https://github.com/lawrencea13/LethalCompanySaveManager/assets/42782213/9564deff-b1e3-4c66-8afd-726fe22dcc09)

Exception occurs when savefile that doesn't exist is selected in dropdown. Clicking continue traverses through this exception just fine but it is clunky with the popup being displayed for the save manager

**Comment by lawrencea13** [comment]
This issue has been fixed with the latest release.
