### ISSUE TITLE
[Feature Idea/Request] Backup Note's

### ISSUE THREAD

**Issue by MineTech13** [lawrencea13/LethalCompanySaveManager#7]
I just got the idea due to an situation i ran into that it would be rly nice to be able to add like a little note or a name to a backup to be able to identify it better i play with a few groups and it gotten quite hard to keep track off what save/backup was now the correct one so if its not to much work this could be an idea ^^

**Comment by lawrencea13** [comment]
Closing as a planned update thanks to a contribution from @Pickendord
