### ISSUE TITLE
Editor Fails to Load Save file, but does not throw exception.

### ISSUE THREAD

**Issue by RyanEskridge** [lawrencea13/LethalCompanySaveManager#8]
Editor Version: Nov 3 Release
LC Version: 45
Mods Installed: No
Windows Version: 10 Pro 22H2

Description:
The program shows expected status messages for each function, but when I play the game, the save has not been edited.

Steps to reproduce:
1. Start Lethal Company, load save, and note variables.
2. Open "LethalCompanySaveManager.exe" either normally or as admin.
3. Click "Load Selected Backup." ("Loaded backup!" status given.)
4. Click "Edit Backup." ("Loaded backup" status given but fields are not populated.)
5. Set coins to 1000, deadline to 4, and quota to 1.
6. Click "Confirm." ("Updated Backup" status given.)
7. Open lethal company and load selected backup.
8. Confirm that variables have not changed.

**Comment by lawrencea13** [comment]
You need to back up the save into a backup slot. This explains why the fields are missing. Though based on how it handled this, there is a bit of an oversight where it doesn't tell you the backup was empty.

**Comment by lawrencea13** [comment]
Due to no response, issue will be closed.
